augmentation_config:
  brightness: 0.2
  contrast: 0.2
  horizontal_flip: 0.5
  hue: 0.1
  mixup: 0.1
  mosaic: 0.3
  rotation: 10
  saturation: 0.2
  vertical_flip: 0.1
data_config:
  annotation_path: data/annotations/coco/instances.json
  dataset_path: data/curated
  num_workers: 2
  pin_memory: true
  train_files:
  - prod_case_001_no_damage.jpg
  - prod_case_002_rust.jpg
  - prod_case_003_dent.jpg
  - prod_case_004_severe.jpg
  val_files:
  - val_case_001_scratch.jpg
  - val_case_002_rust.jpg
  - val_case_003_no_damage.jpg
logging_config:
  log_interval: 10
  log_level: INFO
  save_checkpoints: true
  tensorboard_logging: true
  wandb_logging: false
loss_config:
  box_loss_gain: 7.5
  cls_loss_gain: 0.5
  focal_loss_alpha: 0.25
  focal_loss_gamma: 2.0
  obj_loss_gain: 1.0
  use_knout_pryanik: true
model_config:
  architecture: yolov8n
  input_size: 640
  num_classes: 6
  pretrained: true
training_config:
  batch_size: 4
  early_stopping: true
  epochs: 100
  learning_rate: 0.001
  patience: 20
  save_best_only: true
  weight_decay: 0.0005
validation_config:
  conf_threshold: 0.25
  iou_threshold: 0.45
  save_predictions: true
  visualize_results: true
